server:
  port: 8080

spring:
  data:
    redis:
      host: 192.168.22.128
      port: 6379
      password: 123456
      timeout: 6s
      database: 0

  application:
    name: mall-gateway
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: mall-user-route
          uri: lb://mall-user
          predicates:
            - Path=/api/user/**
          filters:
            - StripPrefix=1
        - id: mall-auth-route
          uri: lb://mall-auth
          predicates:
            - Path=/api/auth/**
          filters:
            - StripPrefix=1
        - id: mall-product-route
          uri: lb://mall-product
          predicates:
            - Path=/api/product/**
          filters:
            - StripPrefix=1
        - id: order-service-route
          uri: lb://mall-order
          predicates:
            - Path=/api/order/**
          filters:
            - StripPrefix=1

jwt:
  secret: "mall-auth-secret-key-mall-auth-secret-key"

mall:
  gateway:
    auth:
      whitelist:
        - /api/auth/login
        - /api/user/register
        - /api/product/search
        - /api/product/page